-- Argus: Museum Security — Phase 1, Step 1
-- Creates three tables for the museum sensor grid:
--   argus_zones          : gallery polygons (the monitored rooms)
--   argus_zone_features  : cameras and artwork as point geometries inside each zone
--   argus_visitor_events : visitor sensor pings (position + behavioral metrics)
--
-- Vector dimensions: [zone_coverage, dwell_normalized, camera_proximity_ratio]
--   zone_coverage        : fraction of the gallery area the visitor has traversed (0-1)
--   dwell_normalized     : minutes spent in zone / 60 (max threshold)
--   camera_proximity_ratio: fraction of movement pings nearest to a camera vs. nearest to artwork (0-1)
--                          Computed dynamically via SDO_GEOM.SDO_DISTANCE against argus_zone_features.

CREATE TABLE argus_zones (
    zone_id   NUMBER PRIMARY KEY,
    zone_name VARCHAR2(100),
    zone_type VARCHAR2(50),   -- 'GALLERY', 'EXHIBIT'
    shape     SDO_GEOMETRY
);

CREATE TABLE argus_zone_features (
    feature_id   NUMBER PRIMARY KEY,
    zone_id      NUMBER,
    feature_type VARCHAR2(20),   -- 'ARTWORK', 'CAMERA'
    feature_name VARCHAR2(100),
    location     SDO_GEOMETRY    -- point geometry of the feature
);

CREATE TABLE argus_visitor_events (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    visitor_id    NUMBER,
    timestamp     TIMESTAMP,
    zone_coverage NUMBER(5,3),   -- 0.00 – 1.00 (fraction of gallery traversed)
    dwell_minutes NUMBER,
    location      SDO_GEOMETRY   -- visitor's position at event time
);

COMMIT;

-- Verification:
-- SELECT table_name FROM user_tables
--   WHERE table_name IN ('ARGUS_ZONES', 'ARGUS_ZONE_FEATURES', 'ARGUS_VISITOR_EVENTS');
