-- Phase 1, Step 1: Database Provisioning & Schema Setup
-- Creates the tables for restricted zones and tracking events.

-- Create Restricted Zones (Schools, etc.)
CREATE TABLE restricted_zones (
    zone_id NUMBER PRIMARY KEY,
    zone_name VARCHAR2(100),
    zone_type VARCHAR2(50), -- 'SCHOOL', 'CRIMINAL_HOTSPOT'
    shape SDO_GEOMETRY
);

-- Create Tracking Events (Ankle Monitor Pings)
CREATE TABLE tracking_events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    parolee_id NUMBER,
    timestamp TIMESTAMP,
    speed_mph NUMBER,
    heading NUMBER,
    location SDO_GEOMETRY
);

-- Grant permissions if needed (adjust username as necessary)
-- GRANT CREATE TABLE to YOUR_USERNAME;
-- GRANT CREATE SEQUENCE to YOUR_USERNAME;

COMMIT;

-- Verification:
-- SELECT table_name FROM user_tables WHERE table_name IN ('RESTRICTED_ZONES', 'TRACKING_EVENTS');
-- Expected: RESTRICTED_ZONES, TRACKING_EVENTS
